services:
  mysql-server:
    image: mysql:5.7
    platform: linux/amd64
    container_name: kotlin-restful-api-db
    hostname: kotlin-restful-api-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: kotlin_api
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      TZ: Asia/Tokyo
    volumes:
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/data:/var/lib/mysql
      - ./docker/init:/docker-entrypoint-initdb.d
    cap_add:
      - SYS_NICE
    networks:
      - container-network

networks:
  container-network:
    name: kotlin-restful-api
